defaults: &defaults
  working_directory: ~/thrift-typescript
  docker:
    - image: circleci/node:6.10.3

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Run Test Suite
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  publish_fix:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Generate .npmrc File
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Build Publish Assets
          command: npm run build
      - run:
          name: Publish to NPM
          command: npm publish --tag fix --access public

workflows:
  version: 2
  build_publish:
      jobs:
        - test:
            filters:
              tags:
                only: /.*/

        - publish_fix:
            requires:
              - test
            filters:
              tags:
                only: /^(v){1}[1]+(\.[0-9]+){2}$/
              branches:
                ignore: /.*/
