defaults: &defaults
  working_directory: ~/thrift-typescript
  docker:
<<<<<<< HEAD
    - image: circleci/node:8.9.3
=======
    - image: circleci/node:8.9.4
>>>>>>> origin/master

version: 2
jobs:
  test_node_8:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Run Test Suite
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test_node_10:
    <<: *defaults
    docker:
<<<<<<< HEAD
      - image: circleci/node:10.14.0
=======
      - image: circleci/node:10.9.0
>>>>>>> origin/master
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Run Test Suite
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Generate .npmrc File
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Build Publish Assets
          command: npm run build
      - run:
          name: Publish to NPM
          command: npm publish --access public

  publish_next:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Generate .npmrc File
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Build Publish Assets
          command: npm run build
      - run:
          name: Publish to NPM
          command: npm publish --tag next --access public

workflows:
  version: 2
  build_publish:
      jobs:
        - test_node_8:
            filters:
              tags:
                only: /.*/

        - test_node_10:
            filters:
              tags:
                only: /.*/

        - publish:
            requires:
              - test_node_8
              - test_node_10
            filters:
              tags:
                only: /^(v){1}[0-9]+(\.[0-9]+){2}$/
              branches:
                ignore: /.*/

        - publish_next:
            requires:
              - test_node_8
              - test_node_10
            filters:
              tags:
                only: /^(v){1}[0-9]+(\.[0-9]+){2}(-)[0-9]+$/
              branches:
                ignore: /.*/
