version: 2
jobs:
  build:
    working_directory: ~/thrift-typescript
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  npm_token:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run:
        command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
  publish:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run:
          name: publish-npm
          command: npm publish

workflows:
  version: 2
  build_publish:
      jobs:
        - publish:
            requires:
              - build
              - npm_token
            filters:
              tag: /(v)?[0-9]+(\.[0-9]+)*/
